{
 "title": "4Pg  Simple Dashboard",
 "description": "My PostgreSQL simple dashboard",
 "tags": [ "MyPg" ],
 "time": { "from": "now-7d", "to": "now+4h" },
 "templating": {
  "list": [
   { "name": "MyInstance", "query": "postgres" },
   {
    "name": "MyVar",
    "query": "select  '<b>' || inet_server_addr() || ':' || inet_server_addr() || '</b>'"
   },
   {
    "name": "MyVar2",
    "query": "select  substring(version() for  position(',' in version())-1) || ' Created at ' || min((pg_stat_file('base/'||oid ||'/PG_VERSION')).modification)   from pg_database"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "content": "<div style=\"text-align: center;\">$MyInstance -- $MyVar</div>"
  },
  {
   "title": "Read Activity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts as time,\n  (sum(heap_blks_read+heap_blks_hit+idx_blks_read+idx_blks_hit)-lag(sum(heap_blks_read+heap_blks_hit+idx_blks_read+idx_blks_hit)) over (order by ts))/600 as value\nFROM pgstatspack_snap s, pgstatspack_tables t\nWHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n   AND s.snapid=t.snapid\nGROUP BY ts\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts as time,\n  count(*) as \"Total\",\n  sum(case working when true then 1 else 0 end) as \"Active\"\nFROM pgstatspack_snap s, pgstatspack_activity_v a\nWHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n   AND s.snapid=a.snapid\nGROUP BY  ts\nORDER BY ts ASC, 2 desc"
    }
   ]
  },
  {
   "title": "Space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select ts as time,\n       sum(sizek)*1024 as size \n  from pgstatspack_space_usage\n WHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by ts\n order by ts\n"
    }
   ]
  },
  {
   "title": "Heap Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.heap_blks_hit)/sum(t.heap_blks_hit+t.heap_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n order by ts"
    }
   ]
  },
  {
   "title": "IDX Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.idx_blks_hit)/sum(t.idx_blks_hit+t.idx_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n order by s.ts\n"
    }
   ]
  },
  {
   "title": "Tuples OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeEpoch(ts),\n       'Read' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.seq_tup_read) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n         GROUP BY s.ts) sum_read\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\nUNION\nselect $__timeEpoch(ts),\n       'Fetch' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.idx_tup_fetch) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n         GROUP BY s.ts) sum_read\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n order by 1 asc, 2 desc\n"
    }
   ]
  },
  {
   "title": "Transactions /sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "select ts as time,\n       'Commit' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(d.xact_commit) as val\n          FROM pgstatspack_database d, pgstatspack_snap s\n         WHERE d.snapid=s.snapid\n         GROUP BY s.ts) sum_comm\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\nUNION\nselect ts as time,\n       'Rollback' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(d.xact_rollback) as val\n          FROM pgstatspack_database d, pgstatspack_snap s\n         WHERE d.snapid=s.snapid\n         GROUP BY s.ts) sum_comm\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n order by 1 asc, 2 desc"
    }
   ]
  },
  {
   "title": "Toast Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.toast_blks_hit)/sum(t.toast_blks_hit+t.toast_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n having sum(t.toast_blks_hit+t.toast_blks_read)>0\n order by s.ts"
    }
   ]
  },
  {
   "title": "Tuples IN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select ts as time,\n       'Inserted' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_ins) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           and ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\nUNION\nselect ts as time,\n       'Updated' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_upd) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\nUNION\nselect ts as time,\n       'Deleted' as metric,\n       -greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_del) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\n order by 1 asc, 2 desc"
    }
   ]
  },
  {
   "title": "Heatmap (#Active)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', ts) as time,\n       ' ' || max(DATE_PART('hour',ts)) as metric,\n       max(val) as value\n  FROM (SELECT ts, sum(case working when true then 1 else 0 end) as val\n          FROM pgstatspack_snap s, pgstatspack_activity_v a\n         WHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n           AND s.snapid=a.snapid\n         GROUP BY ts ) iq\n GROUP BY date_trunc('hour', ts), date_trunc('day', ts)\n ORDER BY 2, 1 "
    }
   ]
  },
  {
   "title": "Toast IDX Cache Hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.tidx_blks_hit)/sum(t.tidx_blks_hit+t.tidx_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n having sum(t.tidx_blks_hit+t.tidx_blks_read)>0\n order by s.ts"
    }
   ]
  },
  {
   "title": "Master - Connected Slaves",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       0 as value \n  FROM pgstatspack_snap s\n WHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n"
    }
   ]
  },
  { "title": "$MyVar2", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 0, "y": 20 } },
  {
   "title": "This dashboard uses pgstatspack (http://www.xenialab.it/meo/web/pub/pgstatspack-2.3.3.zip)",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 20 }
  }
 ]
}