import json 

def convert_to_dict(data:str)->dict: 
   """
   Convert data from JSON to dict
   :args: 
      data:str - data object to convert
   :param: 
      dict_data:dict - data as dictionary 
   :return: 
      dict_data 
   """
   dict_data = {} 
   try:
      dict_data = json.loads(data) 
   except Exception as e: 
      print('Failed to convert data to dict from JSON (Error: %s' % e)

   return dict_data 

def convert_to_json(data:dict)->str: 
   """
   Convert data from dict to JSON 
   :args: 
      data:dict - data object to convert 
   :param: 
      str_data:str - data as string 
   :return: 
      str_data 
   """
   str_data = None 
   try: 
      str_data = json.dumps(data) 
   except Exception as e: 
      print('Failed to convert to string from dict (Error: %s)' % e) 

   return str_data 

def convert_to_str(data:bytes)->str: 
   """
   Convert data from bytes to string
   :args:
      data:bytes - data object to convert
   :param: 
      str_data - data as tring 
   :return: 
      str_data
   """
   str_data = None 
   try: 
      str_data = data.decode()
   except Exception as e: 
      print('Failed to convert bytes to string (Error: %s)' % e) 
   return str_data 


def print_data(rows): 
   """
   for rows print json data
   :args:
      rows:list - daa extracted from grafana DB 
   :print:
      print each row generated by query 
   """
   for row in rows: 
      print(row[0])
       

